### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sachi21** [wishyouhappy/AirlineReservation#2]
3 errors are coming while running the project at  : FlightReservationSystem.initiateFlights(FlightReservationSystem.java:64)
	at FlightReservationSystem.<init>(FlightReservationSystem.java:44)
	at SystemRunner.main(SystemRunner.java:18)

**Comment by sachi21** [comment]
can you suggest me how to correct it

**Comment by christine-1017** [comment]
Could you please add more detailed logs?
